# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify container with the desired Node version 
      - image: circleci/node:latest-browsers

    working_directory: ~/iknowhtml.github.io
    branches:
      only:
        - production
   
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3d:49:45:46:91:75:7b:cd:e0:4d:13:f9:34:b5:15:5d"
      
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install dependencies
          command: yarn install
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build script
      - run: 
          name: Build project
          command: yarn build

      - run:
          name: Deploy to Github Pages
          command: |
            git config user.email "circleci-deployment-bot@iknowht.ml"
            git config user.name "circleci-deployment-bot"
            yarn deploy -m "Build #${CIRCLE_BUILD_NUM} for commit ${CIRCLE_SHA1} from ${CIRCLE_BUILD_URL} [ci skip]"