name: Build and Deploy Personal Site
on:
  push:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Yarn
        uses: actions/setup-node@v2
      - name: Install and Build
        run: |
          yarn install
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: master
          folder: dist