name: Build and Deploy Personal Site
on:
  push:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Node Environment
        uses: actions/setup-node@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm i

      - name: Build Project
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: master
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}